<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile number_mobileNumber</name>
   <tag></tag>
   <elementGuidId>a392e97e-0c29-4f46-b2a5-717063dd6f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mobileNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mobileNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebe70e40-6f03-44cd-b21c-760f76e57155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>phone-number-id</value>
      <webElementGuid>834e8654-f6d5-491f-88ce-fad72ab481c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-white</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7296d67d-423a-41bd-9193-f75410242c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>30df1013-dbc8-4c3e-a392-f6195343e894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobileNumber</value>
      <webElementGuid>9934782f-ec67-46aa-8543-c8931fd41602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3394d028-d9d2-4ec1-b5f9-edae22cf53a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8           </value>
      <webElementGuid>234b750d-2477-40b1-8321-b2052e034e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>0e75a4d3-94e6-4b11-859c-0e258e9c9225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;sc-eDLJxc jROSNv&quot;]/div[@class=&quot;sc-iBdmCd jCpTsi&quot;]/div[@class=&quot;sc-jTQDnj iCjXqL&quot;]/div[@class=&quot;sc-fsYeqs ljsNSP&quot;]/div[@class=&quot;sc-eCywaA erjyoW&quot;]/div[@class=&quot;sc-buPYYr dvImEA&quot;]/form[1]/div[@class=&quot;PhoneNumberInputstyle__PhoneNumberWrapper-sc-sczcc9-0 hehnQs&quot;]/div[@class=&quot;Inputstyle__InputBoxWrapper-sc-5zft4g-0 caFzfe input-box-wrapper&quot;]/div[@class=&quot;Inputstyle__Wrapper-sc-5zft4g-1 kQixGr&quot;]/div[@class=&quot;InputWrapper-sc-mxp6v3-0 cuwgSq input-box-wrapper-child&quot;]/input[1]</value>
      <webElementGuid>60c36557-4da5-43d5-bec3-be8bec090ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mobileNumber']</value>
      <webElementGuid>ad839dbb-5de2-4254-9c0b-42f51aa492c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div/div[2]/div[2]/div/div/form/div/div/div/div/input</value>
      <webElementGuid>4f799fc1-de7d-4bc4-96c2-1f1dd51e5c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cc5e43ab-a8e2-4180-ac75-c1268cdd5591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobileNumber' and @type = 'tel']</value>
      <webElementGuid>48bbb6c4-bd46-4161-91aa-04906a8c72ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
