<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Password_login-password-input</name>
   <tag></tag>
   <elementGuidId>7f8dd5fe-34a4-4e1d-9e2c-811cfcb9a9b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-password-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-password-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5210ad85-7b3a-431d-a2e4-b2aac860cc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-password-input</value>
      <webElementGuid>b0165036-246c-49cf-9024-d236f2325b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>password-input</value>
      <webElementGuid>1745afbf-8de4-4633-be57-116ea96313df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>7459ddce-ee2a-4abc-89ad-05cfa9426d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-password-input</value>
      <webElementGuid>8cf4d3c8-dd45-48ab-a56e-780690a4eb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6443ddb2-9b13-4f5d-8a53-996d1e229ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Inputstyle__StyledInput-sc-5zft4g-4 ktbjuc</value>
      <webElementGuid>da3192e9-3e8c-4d20-82e2-1011485b6696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>487caec7-9023-4de6-99a2-39df4f8f41c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-password-input&quot;)</value>
      <webElementGuid>c5e4c58f-d311-4041-8f9f-93f98200d233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-password-input']</value>
      <webElementGuid>c7e796a2-3ba7-4ac6-9069-ddfae95a119f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div/div[2]/div[2]/div/div/form/div/div/div/div/div/input</value>
      <webElementGuid>7e3bc885-5fa8-4d0b-8615-0f5d08f3ecea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5834782a-7380-4dfb-beee-06869d310900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login-password-input' and @id = 'login-password-input' and @type = 'password']</value>
      <webElementGuid>2c2c5c47-d395-4d27-a1f2-28f10238da26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
