<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_logout</name>
   <tag></tag>
   <elementGuidId>12480d96-fdc2-456a-9cbe-ad2898584141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/section/div[3]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-ctvTVS.cZdVEB > span.Textstyle__TextWrapper-sc-fopj1k-0.OXkyL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6633cf75-8495-4317-bbf9-4c66c1f7df08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>TextWrapper</value>
      <webElementGuid>f3de615c-6f1d-4387-a694-9cb947dcb918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>2ef12e6c-28e3-4b62-aea0-29f9d3d8472c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textstyle__TextWrapper-sc-fopj1k-0 OXkyL</value>
      <webElementGuid>ecc78eed-2a21-4a25-afc5-b531be0e8df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>b1cce726-0bbd-4fae-a05b-1271337721f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-dIoOix goHGfh&quot;]/header[@class=&quot;sc-dPtEPY iSrOpd&quot;]/div[@class=&quot;sc-imjeyh kfTAEv&quot;]/section[@class=&quot;sc-dZYHQZ bBEctb&quot;]/div[@class=&quot;sc-zbPrf jSjBxq&quot;]/div[@class=&quot;sc-ctvTVS cZdVEB&quot;]/span[@class=&quot;Textstyle__TextWrapper-sc-fopj1k-0 OXkyL&quot;]</value>
      <webElementGuid>703dcc2d-6123-4aa5-9656-450e6e5549de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/section/div[3]/div/span</value>
      <webElementGuid>6975d3fe-6e0f-49b5-8f51-55c87f16e4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debi Prasad Sama...'])[1]/following::span[1]</value>
      <webElementGuid>c890dae1-7094-4e63-9d2d-6d2b55f5cbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::span[2]</value>
      <webElementGuid>1a7f3dff-2977-4b4a-bbea-2062c2f65f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Money'])[1]/preceding::span[3]</value>
      <webElementGuid>630a67dd-4fcb-4c51-bff9-ef4da7ca8dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create FD'])[1]/preceding::span[4]</value>
      <webElementGuid>e3b7456e-3cb6-4180-ac8c-3dda43d1c1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='logout']/parent::*</value>
      <webElementGuid>ac7998b8-f709-4a8d-9998-cb2eaacfa67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>156174ac-3a2e-4a78-ae3a-3245920ca0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'logout' or . = 'logout')]</value>
      <webElementGuid>5db312d0-4d72-43e1-83a7-792d8e6fa298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
