<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login securely</name>
   <tag></tag>
   <elementGuidId>1e355de5-797a-4b77-bc54-f9994e935ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/div/div[2]/div[2]/div/div/form/div[3]/button/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Textstyle__TextWrapper-sc-fopj1k-0.heMaQO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f23b2ec8-d118-4a20-817d-f9a7d701609a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>TextWrapper</value>
      <webElementGuid>cf635c6a-b5f2-46e0-890b-225101ffcf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>86e4c064-bb47-4624-bbc6-facd21b8da8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textstyle__TextWrapper-sc-fopj1k-0 heMaQO</value>
      <webElementGuid>0c6bcfeb-9188-4e16-bd1e-e68c18d20d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login securely</value>
      <webElementGuid>bd11b447-32d7-43ac-9d08-f6454422ecb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;sc-eDLJxc jROSNv&quot;]/div[@class=&quot;sc-iBdmCd jCpTsi&quot;]/div[@class=&quot;sc-jTQDnj iCjXqL&quot;]/div[@class=&quot;sc-fsYeqs ljsNSP&quot;]/div[@class=&quot;sc-dnoYJd jwqLBg&quot;]/div[@class=&quot;sc-buPYYr dvImEA&quot;]/form[1]/div[@class=&quot;sc-gvECLv cOtMoW&quot;]/button[@class=&quot;Buttonstyle__Wrapper-sc-6p72tp-0 fiHaVQ&quot;]/span[1]/span[@class=&quot;Textstyle__TextWrapper-sc-fopj1k-0 heMaQO&quot;]</value>
      <webElementGuid>d00a8f37-e5e9-4cef-bd1b-28fd16ca74f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div/div[2]/div[2]/div/div/form/div[3]/button/span/span</value>
      <webElementGuid>8cb14f0a-a35d-4c9b-a814-14999b3139c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::span[2]</value>
      <webElementGuid>b2c30c0c-f4ae-4051-9fa5-ad06eb36a3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp;'])[1]/following::span[2]</value>
      <webElementGuid>5b4c4dce-ef50-4808-b6eb-e2b14a71441d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDFC FIRST Bank is registered with DICGC (https://www.dicgc.org.in)'])[1]/preceding::span[2]</value>
      <webElementGuid>5e74b951-48b7-41e7-9931-c8c2c834637f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DICGC Website'])[1]/preceding::span[3]</value>
      <webElementGuid>c63e705f-0e6a-463d-905f-84a981a07d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login securely']/parent::*</value>
      <webElementGuid>4ea25b71-0669-4bf0-b9b2-96ae7d8720cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/span</value>
      <webElementGuid>2de7290e-2b9a-47a2-8650-ceb0738f1e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login securely' or . = 'Login securely')]</value>
      <webElementGuid>9508830a-e2ba-4f42-a725-5267ee9f1566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
